"""add_sector_tags_to_grants

Revision ID: d9dcd97b8516
Revises: d7a67981ca12
Create Date: 2026-05-21 15:33:59.460253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dcd97b8516'
down_revision: Union[str, Sequence[str], None] = 'd7a67981ca12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('sector_tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grants', 'sector_tags')
    # ### end Alembic commands ###
